spiciness_dict = {
    'tonkotsu ramen': 'mild',
    'japanese style': 'mild',
    'tom yum': 'hot',
    'chicken flavor': 'mild',
    'seafood flavor': 'mild',
    'beef flavor': 'mild',
    'mi goreng': 'mild',
    'black pepper': 'hot',
    'soy sauce': 'mild',
    'chow mein': 'mild', 
    'pork flavor': 'mild',
    'shrimp flavour':'mild', 
    'crab flavour':'mild',
    'seafood flavour': 'mild',
    'xo sauce': 'mild',
    'seafood flavour': 'mild',
    'sesame oil': 'mild',
    'artificial pork': 'mild',
    'chicken soup': 'mild',
    'mi segera': 'mild',
    'penang white': 'hot',
    'yum kung': 'hot',
    'soy paste': 'mild',
    'pancit canton': 'mild',
    'sweet potato': 'mild',
    'kuah rasa': 'mild',
    'rasa ayam': 'mild',
    'bokkeummyun': 'hot',
    'shin ramyun': 'hot',
    'tom yam': 'hot',
    'demae iccho': 'mild',
    'sopa nissin': 'mild',
    'malaysia penang': 'hot',
    'south korean': 'hot'}

spiciness_word = {
    'laksa': 'hot',
    'buldak': 'hot',
    'curry': 'hot',
    'fiery': 'hot',
    'sichuan': 'hot',
    'kimchi': 'hot',
    'udon': 'mild',
    'tempura': 'mild',
    'tonkotsu': 'mild',
    'shoyu': 'mild',
    'korean': 'hot',
    'shio': 'mild', 
    'creamy' : 'mild',
    'demae': 'mild',
    'artificial': 'mild'}